controller_joint_names: [r_gripper_l_finger_joint, right_j0, right_j1, right_j2, right_j3, right_j4, right_j5, right_j6]

#controller_joint_names: [right_j0, right_j1, right_j2, right_j3, right_j4, right_j5, right_j6]